#ifndef _FGFP_GRM_H_
#define _FGFP_GRM_H_

#define _ONLY_TOKEN_	
#include "fgfx.lex.h"
#undef	_ONLY_TOKEN_

enum {
	N_FGFP,
	N_section,
	N_extern_section,
	N_production_section,
	N_alias_section,
	N_prec_section,
	N_path_list,
	N_path_list_PRIME,
	N_alias_list,
	N_alias_list_PRIME,
	N_prec_list,
	N_prec_dir,
	N_prec_atom_list,
	N_prec_list_PRIME,
	N_prec_atom,
	N_prec_atom_list_PRIME,
	N_prec_atom_list_PRIME_PRIME,
	N_production_list,
	N_production,
	N_production_list_PRIME,
	N_follow_prod,
	N_rhs,
	N_opt_list,
	N_mimic,
	N_rhs_PRIME,
	N_symbol_list,
	N_symbol,
	N_symbol_list_PRIME,
};

#define TOTAL_NTER	28

enum {
	P_LHS_NFGFP_RHS_Nsection_NFGFP,
	P_LHS_NFGFP_RHS,
	P_LHS_Nsection_RHS_Nextern_section,
	P_LHS_Nsection_RHS_Nproduction_section,
	P_LHS_Nsection_RHS_Nalias_section,
	P_LHS_Nsection_RHS_Nprec_section,
	P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI,
	P_LHS_Npath_list_RHS_TLITERAL_Npath_list_PRIME,
	P_LHS_Npath_list_RHS,
	P_LHS_Npath_list_PRIME_RHS_TCOMMA_Npath_list,
	P_LHS_Npath_list_PRIME_RHS,
	P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI,
	P_LHS_Nalias_list_RHS_TLPAREN_TGLOBAL_TOK_TBARROW_TLITERAL_TRPAREN_Nalias_list_PRIME,
	P_LHS_Nalias_list_RHS,
	P_LHS_Nalias_list_PRIME_RHS_TCOMMA_Nalias_list,
	P_LHS_Nalias_list_PRIME_RHS,
	P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI,
	P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME,
	P_LHS_Nprec_list_RHS,
	P_LHS_Nprec_list_PRIME_RHS_TCOMMA_Nprec_list,
	P_LHS_Nprec_list_PRIME_RHS,
	P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME,
	P_LHS_Nprec_atom_list_PRIME_RHS_TCOMMA_Nprec_atom_list_PRIME_PRIME,
	P_LHS_Nprec_atom_list_PRIME_RHS,
	P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME,
	P_LHS_Nprec_atom_list_PRIME_PRIME_RHS,
	P_LHS_Nprec_atom_RHS_TGLOBAL_TOK,
	P_LHS_Nprec_atom_RHS_TLITERAL,
	P_LHS_Nprec_dir_RHS_TLEFT,
	P_LHS_Nprec_dir_RHS_TRIGHT,
	P_LHS_Nprec_dir_RHS_TNONASSOC,
	P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI,
	P_LHS_Nproduction_list_RHS_Nproduction_Nproduction_list_PRIME,
	P_LHS_Nproduction_list_RHS,
	P_LHS_Nproduction_list_PRIME_RHS_Nproduction_Nproduction_list_PRIME,
	P_LHS_Nproduction_list_PRIME_RHS,
	P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI,
	P_LHS_Nfollow_prod_RHS_TEQUAL_TSTART,
	P_LHS_Nfollow_prod_RHS_TARROW_Nrhs,
	P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME,
	P_LHS_Nrhs_PRIME_RHS_TUNION_Nopt_list_Nmimic_Nrhs_PRIME,
	P_LHS_Nrhs_PRIME_RHS,
	P_LHS_Nopt_list_RHS_Nsymbol_list,
	P_LHS_Nopt_list_RHS_TEMPTY,
	P_LHS_Nopt_list_RHS,
	P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME,
	P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME,
	P_LHS_Nsymbol_list_PRIME_RHS,
	P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN,
	P_LHS_Nsymbol_RHS_TGLOBAL_TOK,
	P_LHS_Nsymbol_RHS_TNTER,
	P_LHS_Nsymbol_RHS_TLITERAL,
};

#define TOTAL_PROD	53

static int
fgfp_rhs_prod_table[TOTAL_PROD] = {
	[P_LHS_NFGFP_RHS_Nsection_NFGFP] = 2,
	[P_LHS_NFGFP_RHS] = 0,
	[P_LHS_Nsection_RHS_Nextern_section] = 1,
	[P_LHS_Nsection_RHS_Nproduction_section] = 1,
	[P_LHS_Nsection_RHS_Nalias_section] = 1,
	[P_LHS_Nsection_RHS_Nprec_section] = 1,
	[P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI] = 5,
	[P_LHS_Npath_list_RHS_TLITERAL_Npath_list_PRIME] = 2,
	[P_LHS_Npath_list_RHS] = 0,
	[P_LHS_Npath_list_PRIME_RHS_TCOMMA_Npath_list] = 2,
	[P_LHS_Npath_list_PRIME_RHS] = 0,
	[P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI] = 5,
	[P_LHS_Nalias_list_RHS_TLPAREN_TGLOBAL_TOK_TBARROW_TLITERAL_TRPAREN_Nalias_list_PRIME] = 6,
	[P_LHS_Nalias_list_RHS] = 0,
	[P_LHS_Nalias_list_PRIME_RHS_TCOMMA_Nalias_list] = 2,
	[P_LHS_Nalias_list_PRIME_RHS] = 0,
	[P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI] = 5,
	[P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME] = 5,
	[P_LHS_Nprec_list_RHS] = 0,
	[P_LHS_Nprec_list_PRIME_RHS_TCOMMA_Nprec_list] = 2,
	[P_LHS_Nprec_list_PRIME_RHS] = 0,
	[P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME] = 2,
	[P_LHS_Nprec_atom_list_PRIME_RHS_TCOMMA_Nprec_atom_list_PRIME_PRIME] = 2,
	[P_LHS_Nprec_atom_list_PRIME_RHS] = 0,
	[P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME] = 2,
	[P_LHS_Nprec_atom_list_PRIME_PRIME_RHS] = 0,
	[P_LHS_Nprec_atom_RHS_TGLOBAL_TOK] = 1,
	[P_LHS_Nprec_atom_RHS_TLITERAL] = 1,
	[P_LHS_Nprec_dir_RHS_TLEFT] = 1,
	[P_LHS_Nprec_dir_RHS_TRIGHT] = 1,
	[P_LHS_Nprec_dir_RHS_TNONASSOC] = 1,
	[P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI] = 5,
	[P_LHS_Nproduction_list_RHS_Nproduction_Nproduction_list_PRIME] = 2,
	[P_LHS_Nproduction_list_RHS] = 0,
	[P_LHS_Nproduction_list_PRIME_RHS_Nproduction_Nproduction_list_PRIME] = 2,
	[P_LHS_Nproduction_list_PRIME_RHS] = 0,
	[P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI] = 3,
	[P_LHS_Nfollow_prod_RHS_TEQUAL_TSTART] = 2,
	[P_LHS_Nfollow_prod_RHS_TARROW_Nrhs] = 2,
	[P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME] = 3,
	[P_LHS_Nrhs_PRIME_RHS_TUNION_Nopt_list_Nmimic_Nrhs_PRIME] = 4,
	[P_LHS_Nrhs_PRIME_RHS] = 0,
	[P_LHS_Nopt_list_RHS_Nsymbol_list] = 1,
	[P_LHS_Nopt_list_RHS_TEMPTY] = 1,
	[P_LHS_Nopt_list_RHS] = 0,
	[P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME] = 2,
	[P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME] = 2,
	[P_LHS_Nsymbol_list_PRIME_RHS] = 0,
	[P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN] = 4,
	[P_LHS_Nsymbol_RHS_TGLOBAL_TOK] = 1,
	[P_LHS_Nsymbol_RHS_TNTER] = 1,
	[P_LHS_Nsymbol_RHS_TLITERAL] = 1,
};

static int
fgfp_lhs_prod_table[TOTAL_PROD] = {
	[P_LHS_NFGFP_RHS_Nsection_NFGFP] = N_FGFP,
	[P_LHS_NFGFP_RHS] = N_FGFP,
	[P_LHS_Nsection_RHS_Nextern_section] = N_section,
	[P_LHS_Nsection_RHS_Nproduction_section] = N_section,
	[P_LHS_Nsection_RHS_Nalias_section] = N_section,
	[P_LHS_Nsection_RHS_Nprec_section] = N_section,
	[P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI] = N_extern_section,
	[P_LHS_Npath_list_RHS_TLITERAL_Npath_list_PRIME] = N_path_list,
	[P_LHS_Npath_list_RHS] = N_path_list,
	[P_LHS_Npath_list_PRIME_RHS_TCOMMA_Npath_list] = N_path_list_PRIME,
	[P_LHS_Npath_list_PRIME_RHS] = N_path_list_PRIME,
	[P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI] = N_alias_section,
	[P_LHS_Nalias_list_RHS_TLPAREN_TGLOBAL_TOK_TBARROW_TLITERAL_TRPAREN_Nalias_list_PRIME] = N_alias_list,
	[P_LHS_Nalias_list_RHS] = N_alias_list,
	[P_LHS_Nalias_list_PRIME_RHS_TCOMMA_Nalias_list] = N_alias_list_PRIME,
	[P_LHS_Nalias_list_PRIME_RHS] = N_alias_list_PRIME,
	[P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI] = N_prec_section,
	[P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME] = N_prec_list,
	[P_LHS_Nprec_list_RHS] = N_prec_list,
	[P_LHS_Nprec_list_PRIME_RHS_TCOMMA_Nprec_list] = N_prec_list_PRIME,
	[P_LHS_Nprec_list_PRIME_RHS] = N_prec_list_PRIME,
	[P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME] = N_prec_atom_list,
	[P_LHS_Nprec_atom_list_PRIME_RHS_TCOMMA_Nprec_atom_list_PRIME_PRIME] = N_prec_atom_list_PRIME,
	[P_LHS_Nprec_atom_list_PRIME_RHS] = N_prec_atom_list_PRIME,
	[P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME] = N_prec_atom_list_PRIME_PRIME,
	[P_LHS_Nprec_atom_list_PRIME_PRIME_RHS] = N_prec_atom_list_PRIME_PRIME,
	[P_LHS_Nprec_atom_RHS_TGLOBAL_TOK] = N_prec_atom,
	[P_LHS_Nprec_atom_RHS_TLITERAL] = N_prec_atom,
	[P_LHS_Nprec_dir_RHS_TLEFT] = N_prec_dir,
	[P_LHS_Nprec_dir_RHS_TRIGHT] = N_prec_dir,
	[P_LHS_Nprec_dir_RHS_TNONASSOC] = N_prec_dir,
	[P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI] = N_production_section,
	[P_LHS_Nproduction_list_RHS_Nproduction_Nproduction_list_PRIME] = N_production_list,
	[P_LHS_Nproduction_list_RHS] = N_production_list,
	[P_LHS_Nproduction_list_PRIME_RHS_Nproduction_Nproduction_list_PRIME] = N_production_list_PRIME,
	[P_LHS_Nproduction_list_PRIME_RHS] = N_production_list_PRIME,
	[P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI] = N_production,
	[P_LHS_Nfollow_prod_RHS_TEQUAL_TSTART] = N_follow_prod,
	[P_LHS_Nfollow_prod_RHS_TARROW_Nrhs] = N_follow_prod,
	[P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME] = N_rhs,
	[P_LHS_Nrhs_PRIME_RHS_TUNION_Nopt_list_Nmimic_Nrhs_PRIME] = N_rhs_PRIME,
	[P_LHS_Nrhs_PRIME_RHS] = N_rhs_PRIME,
	[P_LHS_Nopt_list_RHS_Nsymbol_list] = N_opt_list,
	[P_LHS_Nopt_list_RHS_TEMPTY] = N_opt_list,
	[P_LHS_Nopt_list_RHS] = N_opt_list,
	[P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME] = N_symbol_list,
	[P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME] = N_symbol_list_PRIME,
	[P_LHS_Nsymbol_list_PRIME_RHS] = N_symbol_list_PRIME,
	[P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN] = N_mimic,
	[P_LHS_Nsymbol_RHS_TGLOBAL_TOK] = N_symbol,
	[P_LHS_Nsymbol_RHS_TNTER] = N_symbol,
	[P_LHS_Nsymbol_RHS_TLITERAL] = N_symbol,
};

#define ERROR_SLOT	0
#define START_SYMBOL	N_FGFP

static int
fgfp_ll_table[TOTAL_NTER][TOTAL_TOKEN] = {
	[N_FGFP][T_EOF]=P_LHS_NFGFP_RHS, [N_FGFP][T_PRECEDENCE]=P_LHS_NFGFP_RHS_Nsection_NFGFP, [N_FGFP][T_PRODUCTION]=P_LHS_NFGFP_RHS_Nsection_NFGFP, [N_FGFP][T_ALIAS]=P_LHS_NFGFP_RHS_Nsection_NFGFP, [N_FGFP][T_EXTERN]=P_LHS_NFGFP_RHS_Nsection_NFGFP, 
	[N_section][T_PRECEDENCE]=P_LHS_Nsection_RHS_Nprec_section, [N_section][T_ALIAS]=P_LHS_Nsection_RHS_Nalias_section, [N_section][T_PRODUCTION]=P_LHS_Nsection_RHS_Nproduction_section, [N_section][T_EXTERN]=P_LHS_Nsection_RHS_Nextern_section, 
	[N_extern_section][T_EXTERN]=P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI, 
	[N_production_section][T_PRODUCTION]=P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI, 
	[N_alias_section][T_ALIAS]=P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI, 
	[N_prec_section][T_PRECEDENCE]=P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI, 
	[N_path_list][T_RBRACE]=P_LHS_Npath_list_RHS, [N_path_list][T_LITERAL]=P_LHS_Npath_list_RHS_TLITERAL_Npath_list_PRIME, 
	[N_path_list_PRIME][T_RBRACE]=P_LHS_Npath_list_PRIME_RHS, [N_path_list_PRIME][T_COMMA]=P_LHS_Npath_list_PRIME_RHS_TCOMMA_Npath_list, 
	[N_alias_list][T_RBRACE]=P_LHS_Nalias_list_RHS, [N_alias_list][T_LPAREN]=P_LHS_Nalias_list_RHS_TLPAREN_TGLOBAL_TOK_TBARROW_TLITERAL_TRPAREN_Nalias_list_PRIME, 
	[N_alias_list_PRIME][T_RBRACE]=P_LHS_Nalias_list_PRIME_RHS, [N_alias_list_PRIME][T_COMMA]=P_LHS_Nalias_list_PRIME_RHS_TCOMMA_Nalias_list, 
	[N_prec_list][T_RBRACE]=P_LHS_Nprec_list_RHS, [N_prec_list][T_NONASSOC]=P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME, [N_prec_list][T_RIGHT]=P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME, [N_prec_list][T_LEFT]=P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME, 
	[N_prec_dir][T_NONASSOC]=P_LHS_Nprec_dir_RHS_TNONASSOC, [N_prec_dir][T_RIGHT]=P_LHS_Nprec_dir_RHS_TRIGHT, [N_prec_dir][T_LEFT]=P_LHS_Nprec_dir_RHS_TLEFT, 
	[N_prec_atom_list][T_GLOBAL_TOK]=P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME, [N_prec_atom_list][T_LITERAL]=P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME, 
	[N_prec_list_PRIME][T_RBRACE]=P_LHS_Nprec_list_PRIME_RHS, [N_prec_list_PRIME][T_COMMA]=P_LHS_Nprec_list_PRIME_RHS_TCOMMA_Nprec_list, 
	[N_prec_atom][T_LITERAL]=P_LHS_Nprec_atom_RHS_TLITERAL, [N_prec_atom][T_GLOBAL_TOK]=P_LHS_Nprec_atom_RHS_TGLOBAL_TOK, 
	[N_prec_atom_list_PRIME][T_RPAREN]=P_LHS_Nprec_atom_list_PRIME_RHS, [N_prec_atom_list_PRIME][T_COMMA]=P_LHS_Nprec_atom_list_PRIME_RHS_TCOMMA_Nprec_atom_list_PRIME_PRIME, 
	[N_prec_atom_list_PRIME_PRIME][T_RPAREN]=P_LHS_Nprec_atom_list_PRIME_PRIME_RHS, [N_prec_atom_list_PRIME_PRIME][T_GLOBAL_TOK]=P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME, [N_prec_atom_list_PRIME_PRIME][T_LITERAL]=P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME, 
	[N_production_list][T_RBRACE]=P_LHS_Nproduction_list_RHS, [N_production_list][T_NTER]=P_LHS_Nproduction_list_RHS_Nproduction_Nproduction_list_PRIME, 
	[N_production][T_NTER]=P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI, 
	[N_production_list_PRIME][T_RBRACE]=P_LHS_Nproduction_list_PRIME_RHS, [N_production_list_PRIME][T_NTER]=P_LHS_Nproduction_list_PRIME_RHS_Nproduction_Nproduction_list_PRIME, 
	[N_follow_prod][T_ARROW]=P_LHS_Nfollow_prod_RHS_TARROW_Nrhs, [N_follow_prod][T_EQUAL]=P_LHS_Nfollow_prod_RHS_TEQUAL_TSTART, 
	[N_rhs][T_LPAREN]=P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME, [N_rhs][T_EMPTY]=P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME, [N_rhs][T_NTER]=P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME, [N_rhs][T_GLOBAL_TOK]=P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME, [N_rhs][T_LITERAL]=P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME, 
	[N_opt_list][T_LPAREN]=P_LHS_Nopt_list_RHS, [N_opt_list][T_EMPTY]=P_LHS_Nopt_list_RHS_TEMPTY, [N_opt_list][T_NTER]=P_LHS_Nopt_list_RHS_Nsymbol_list, [N_opt_list][T_GLOBAL_TOK]=P_LHS_Nopt_list_RHS_Nsymbol_list, [N_opt_list][T_LITERAL]=P_LHS_Nopt_list_RHS_Nsymbol_list, 
	[N_mimic][T_LPAREN]=P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN, 
	[N_rhs_PRIME][T_SEMI]=P_LHS_Nrhs_PRIME_RHS, [N_rhs_PRIME][T_UNION]=P_LHS_Nrhs_PRIME_RHS_TUNION_Nopt_list_Nmimic_Nrhs_PRIME, 
	[N_symbol_list][T_NTER]=P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME, [N_symbol_list][T_GLOBAL_TOK]=P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME, [N_symbol_list][T_LITERAL]=P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME, 
	[N_symbol][T_LITERAL]=P_LHS_Nsymbol_RHS_TLITERAL, [N_symbol][T_NTER]=P_LHS_Nsymbol_RHS_TNTER, [N_symbol][T_GLOBAL_TOK]=P_LHS_Nsymbol_RHS_TGLOBAL_TOK, 
	[N_symbol_list_PRIME][T_LPAREN]=P_LHS_Nsymbol_list_PRIME_RHS, [N_symbol_list_PRIME][T_NTER]=P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME, [N_symbol_list_PRIME][T_GLOBAL_TOK]=P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME, [N_symbol_list_PRIME][T_LITERAL]=P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME, 
};

#if 0

enum {
	_SHIFT	= 0x1000,
	_REDUCE	= 0x2000,
	_GOTO	= 0x4000,
};

#define SHIFT(x)	(x | _SHIFT)
#define REDUCE(x)	(x | _REDUCE)
#define GOTO(x)	(x | _GOTO)
#define ACCEPT	(~0)

#define LR_START_STATE	0

static int
fgfp_lr_action_table[89][TOTAL_TOKEN] = {
/*   0 */	{[T_PRODUCTION]=SHIFT(10), [T_PRECEDENCE]=SHIFT(9), [T_ALIAS]=SHIFT(8), [T_EXTERN]=SHIFT(7), [T_EOF]=REDUCE(P_LHS_NFGFP_RHS)},
/*   1 */	{[T_EOF]=ACCEPT,},
/*   2 */	{[T_PRODUCTION]=SHIFT(10), [T_PRECEDENCE]=SHIFT(9), [T_ALIAS]=SHIFT(8), [T_EXTERN]=SHIFT(7), [T_EOF]=REDUCE(P_LHS_NFGFP_RHS)},
/*   3 */	{[T_EOF]=REDUCE(P_LHS_Nsection_RHS_Nextern_section), [T_PRECEDENCE]=REDUCE(P_LHS_Nsection_RHS_Nextern_section), [T_PRODUCTION]=REDUCE(P_LHS_Nsection_RHS_Nextern_section), [T_ALIAS]=REDUCE(P_LHS_Nsection_RHS_Nextern_section), [T_EXTERN]=REDUCE(P_LHS_Nsection_RHS_Nextern_section)},
/*   4 */	{[T_EOF]=REDUCE(P_LHS_Nsection_RHS_Nproduction_section), [T_PRECEDENCE]=REDUCE(P_LHS_Nsection_RHS_Nproduction_section), [T_PRODUCTION]=REDUCE(P_LHS_Nsection_RHS_Nproduction_section), [T_ALIAS]=REDUCE(P_LHS_Nsection_RHS_Nproduction_section), [T_EXTERN]=REDUCE(P_LHS_Nsection_RHS_Nproduction_section)},
/*   5 */	{[T_EOF]=REDUCE(P_LHS_Nsection_RHS_Nalias_section), [T_PRECEDENCE]=REDUCE(P_LHS_Nsection_RHS_Nalias_section), [T_PRODUCTION]=REDUCE(P_LHS_Nsection_RHS_Nalias_section), [T_ALIAS]=REDUCE(P_LHS_Nsection_RHS_Nalias_section), [T_EXTERN]=REDUCE(P_LHS_Nsection_RHS_Nalias_section)},
/*   6 */	{[T_EOF]=REDUCE(P_LHS_Nsection_RHS_Nprec_section), [T_PRECEDENCE]=REDUCE(P_LHS_Nsection_RHS_Nprec_section), [T_PRODUCTION]=REDUCE(P_LHS_Nsection_RHS_Nprec_section), [T_ALIAS]=REDUCE(P_LHS_Nsection_RHS_Nprec_section), [T_EXTERN]=REDUCE(P_LHS_Nsection_RHS_Nprec_section)},
/*   7 */	{[T_LBRACE]=SHIFT(14)},
/*   8 */	{[T_LBRACE]=SHIFT(13)},
/*   9 */	{[T_LBRACE]=SHIFT(12)},
/*  10 */	{[T_LBRACE]=SHIFT(11)},
/*  11 */	{[T_NTER]=SHIFT(27), [T_RBRACE]=REDUCE(P_LHS_Nproduction_list_RHS)},
/*  12 */	{[T_NONASSOC]=SHIFT(24), [T_RIGHT]=SHIFT(23), [T_LEFT]=SHIFT(22), [T_RBRACE]=REDUCE(P_LHS_Nprec_list_RHS)},
/*  13 */	{[T_LPAREN]=SHIFT(19), [T_RBRACE]=REDUCE(P_LHS_Nalias_list_RHS)},
/*  14 */	{[T_LITERAL]=SHIFT(17), [T_RBRACE]=REDUCE(P_LHS_Npath_list_RHS)},
/*  15 */	{[T_EOF]=REDUCE(P_LHS_NFGFP_RHS_Nsection_NFGFP)},
/*  16 */	{[T_RBRACE]=SHIFT(40)},
/*  17 */	{[T_COMMA]=SHIFT(39), [T_RBRACE]=REDUCE(P_LHS_Npath_list_PRIME_RHS)},
/*  18 */	{[T_RBRACE]=SHIFT(37)},
/*  19 */	{[T_GLOBAL_TOK]=SHIFT(36)},
/*  20 */	{[T_RBRACE]=SHIFT(35)},
/*  21 */	{[T_LPAREN]=SHIFT(34)},
/*  22 */	{[T_LPAREN]=REDUCE(P_LHS_Nprec_dir_RHS_TLEFT)},
/*  23 */	{[T_LPAREN]=REDUCE(P_LHS_Nprec_dir_RHS_TRIGHT)},
/*  24 */	{[T_LPAREN]=REDUCE(P_LHS_Nprec_dir_RHS_TNONASSOC)},
/*  25 */	{[T_RBRACE]=SHIFT(33)},
/*  26 */	{[T_NTER]=SHIFT(27), [T_RBRACE]=REDUCE(P_LHS_Nproduction_list_PRIME_RHS)},
/*  27 */	{[T_ARROW]=SHIFT(30), [T_EQUAL]=SHIFT(29)},
/*  28 */	{[T_SEMI]=SHIFT(61)},
/*  29 */	{[T_START]=SHIFT(60)},
/*  30 */	{[T_LITERAL]=SHIFT(59), [T_NTER]=SHIFT(58), [T_GLOBAL_TOK]=SHIFT(57), [T_EMPTY]=SHIFT(55), [T_LPAREN]=REDUCE(P_LHS_Nopt_list_RHS)},
/*  31 */	{[T_RBRACE]=REDUCE(P_LHS_Nproduction_list_RHS_Nproduction_Nproduction_list_PRIME)},
/*  32 */	{[T_NTER]=SHIFT(27), [T_RBRACE]=REDUCE(P_LHS_Nproduction_list_PRIME_RHS)},
/*  33 */	{[T_SEMI]=SHIFT(50)},
/*  34 */	{[T_LITERAL]=SHIFT(49), [T_GLOBAL_TOK]=SHIFT(48)},
/*  35 */	{[T_SEMI]=SHIFT(45)},
/*  36 */	{[T_BARROW]=SHIFT(44)},
/*  37 */	{[T_SEMI]=SHIFT(43)},
/*  38 */	{[T_RBRACE]=REDUCE(P_LHS_Npath_list_RHS_TLITERAL_Npath_list_PRIME)},
/*  39 */	{[T_LITERAL]=SHIFT(17), [T_RBRACE]=REDUCE(P_LHS_Npath_list_RHS)},
/*  40 */	{[T_SEMI]=SHIFT(41)},
/*  41 */	{[T_EOF]=REDUCE(P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI), [T_PRECEDENCE]=REDUCE(P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI), [T_PRODUCTION]=REDUCE(P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI), [T_ALIAS]=REDUCE(P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI), [T_EXTERN]=REDUCE(P_LHS_Nextern_section_RHS_TEXTERN_TLBRACE_Npath_list_TRBRACE_TSEMI)},
/*  42 */	{[T_RBRACE]=REDUCE(P_LHS_Npath_list_PRIME_RHS_TCOMMA_Npath_list)},
/*  43 */	{[T_EOF]=REDUCE(P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI), [T_PRECEDENCE]=REDUCE(P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI), [T_PRODUCTION]=REDUCE(P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI), [T_ALIAS]=REDUCE(P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI), [T_EXTERN]=REDUCE(P_LHS_Nalias_section_RHS_TALIAS_TLBRACE_Nalias_list_TRBRACE_TSEMI)},
/*  44 */	{[T_LITERAL]=SHIFT(69)},
/*  45 */	{[T_EOF]=REDUCE(P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI), [T_PRECEDENCE]=REDUCE(P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI), [T_PRODUCTION]=REDUCE(P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI), [T_ALIAS]=REDUCE(P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI), [T_EXTERN]=REDUCE(P_LHS_Nprec_section_RHS_TPRECEDENCE_TLBRACE_Nprec_list_TRBRACE_TSEMI)},
/*  46 */	{[T_RPAREN]=SHIFT(68)},
/*  47 */	{[T_COMMA]=SHIFT(67), [T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_PRIME_RHS)},
/*  48 */	{[T_RPAREN]=REDUCE(P_LHS_Nprec_atom_RHS_TGLOBAL_TOK), [T_COMMA]=REDUCE(P_LHS_Nprec_atom_RHS_TGLOBAL_TOK)},
/*  49 */	{[T_RPAREN]=REDUCE(P_LHS_Nprec_atom_RHS_TLITERAL), [T_COMMA]=REDUCE(P_LHS_Nprec_atom_RHS_TLITERAL)},
/*  50 */	{[T_EOF]=REDUCE(P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI), [T_PRECEDENCE]=REDUCE(P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI), [T_PRODUCTION]=REDUCE(P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI), [T_ALIAS]=REDUCE(P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI), [T_EXTERN]=REDUCE(P_LHS_Nproduction_section_RHS_TPRODUCTION_TLBRACE_Nproduction_list_TRBRACE_TSEMI)},
/*  51 */	{[T_RBRACE]=REDUCE(P_LHS_Nproduction_list_PRIME_RHS_Nproduction_Nproduction_list_PRIME)},
/*  52 */	{[T_SEMI]=REDUCE(P_LHS_Nfollow_prod_RHS_TARROW_Nrhs)},
/*  53 */	{[T_LPAREN]=SHIFT(65)},
/*  54 */	{[T_LPAREN]=REDUCE(P_LHS_Nopt_list_RHS_Nsymbol_list)},
/*  55 */	{[T_LPAREN]=REDUCE(P_LHS_Nopt_list_RHS_TEMPTY)},
/*  56 */	{[T_LITERAL]=SHIFT(59), [T_NTER]=SHIFT(58), [T_GLOBAL_TOK]=SHIFT(57), [T_LPAREN]=REDUCE(P_LHS_Nsymbol_list_PRIME_RHS)},
/*  57 */	{[T_LPAREN]=REDUCE(P_LHS_Nsymbol_RHS_TGLOBAL_TOK), [T_NTER]=REDUCE(P_LHS_Nsymbol_RHS_TGLOBAL_TOK), [T_GLOBAL_TOK]=REDUCE(P_LHS_Nsymbol_RHS_TGLOBAL_TOK), [T_LITERAL]=REDUCE(P_LHS_Nsymbol_RHS_TGLOBAL_TOK)},
/*  58 */	{[T_LPAREN]=REDUCE(P_LHS_Nsymbol_RHS_TNTER), [T_NTER]=REDUCE(P_LHS_Nsymbol_RHS_TNTER), [T_GLOBAL_TOK]=REDUCE(P_LHS_Nsymbol_RHS_TNTER), [T_LITERAL]=REDUCE(P_LHS_Nsymbol_RHS_TNTER)},
/*  59 */	{[T_LPAREN]=REDUCE(P_LHS_Nsymbol_RHS_TLITERAL), [T_NTER]=REDUCE(P_LHS_Nsymbol_RHS_TLITERAL), [T_GLOBAL_TOK]=REDUCE(P_LHS_Nsymbol_RHS_TLITERAL), [T_LITERAL]=REDUCE(P_LHS_Nsymbol_RHS_TLITERAL)},
/*  60 */	{[T_SEMI]=REDUCE(P_LHS_Nfollow_prod_RHS_TEQUAL_TSTART)},
/*  61 */	{[T_RBRACE]=REDUCE(P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI), [T_NTER]=REDUCE(P_LHS_Nproduction_RHS_TNTER_Nfollow_prod_TSEMI)},
/*  62 */	{[T_LPAREN]=REDUCE(P_LHS_Nsymbol_list_RHS_Nsymbol_Nsymbol_list_PRIME)},
/*  63 */	{[T_LITERAL]=SHIFT(59), [T_NTER]=SHIFT(58), [T_GLOBAL_TOK]=SHIFT(57), [T_LPAREN]=REDUCE(P_LHS_Nsymbol_list_PRIME_RHS)},
/*  64 */	{[T_UNION]=SHIFT(77), [T_SEMI]=REDUCE(P_LHS_Nrhs_PRIME_RHS)},
/*  65 */	{[T_MIMIC]=SHIFT(75)},
/*  66 */	{[T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_RHS_Nprec_atom_Nprec_atom_list_PRIME)},
/*  67 */	{[T_LITERAL]=SHIFT(49), [T_GLOBAL_TOK]=SHIFT(48), [T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_PRIME_PRIME_RHS)},
/*  68 */	{[T_COMMA]=SHIFT(72), [T_RBRACE]=REDUCE(P_LHS_Nprec_list_PRIME_RHS)},
/*  69 */	{[T_RPAREN]=SHIFT(70)},
/*  70 */	{[T_COMMA]=SHIFT(84), [T_RBRACE]=REDUCE(P_LHS_Nalias_list_PRIME_RHS)},
/*  71 */	{[T_RBRACE]=REDUCE(P_LHS_Nprec_list_RHS_Nprec_dir_TLPAREN_Nprec_atom_list_TRPAREN_Nprec_list_PRIME)},
/*  72 */	{[T_NONASSOC]=SHIFT(24), [T_RIGHT]=SHIFT(23), [T_LEFT]=SHIFT(22), [T_RBRACE]=REDUCE(P_LHS_Nprec_list_RHS)},
/*  73 */	{[T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_PRIME_RHS_TCOMMA_Nprec_atom_list_PRIME_PRIME)},
/*  74 */	{[T_COMMA]=SHIFT(67), [T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_PRIME_RHS)},
/*  75 */	{[T_LITERAL]=SHIFT(49), [T_GLOBAL_TOK]=SHIFT(48)},
/*  76 */	{[T_SEMI]=REDUCE(P_LHS_Nrhs_RHS_Nopt_list_Nmimic_Nrhs_PRIME)},
/*  77 */	{[T_LITERAL]=SHIFT(59), [T_NTER]=SHIFT(58), [T_GLOBAL_TOK]=SHIFT(57), [T_EMPTY]=SHIFT(55), [T_LPAREN]=REDUCE(P_LHS_Nopt_list_RHS)},
/*  78 */	{[T_LPAREN]=REDUCE(P_LHS_Nsymbol_list_PRIME_RHS_Nsymbol_Nsymbol_list_PRIME)},
/*  79 */	{[T_LPAREN]=SHIFT(65)},
/*  80 */	{[T_RPAREN]=SHIFT(86)},
/*  81 */	{[T_RPAREN]=REDUCE(P_LHS_Nprec_atom_list_PRIME_PRIME_RHS_Nprec_atom_Nprec_atom_list_PRIME)},
/*  82 */	{[T_RBRACE]=REDUCE(P_LHS_Nprec_list_PRIME_RHS_TCOMMA_Nprec_list)},
/*  83 */	{[T_RBRACE]=REDUCE(P_LHS_Nalias_list_RHS_TLPAREN_TGLOBAL_TOK_TBARROW_TLITERAL_TRPAREN_Nalias_list_PRIME)},
/*  84 */	{[T_LPAREN]=SHIFT(19), [T_RBRACE]=REDUCE(P_LHS_Nalias_list_RHS)},
/*  85 */	{[T_RBRACE]=REDUCE(P_LHS_Nalias_list_PRIME_RHS_TCOMMA_Nalias_list)},
/*  86 */	{[T_UNION]=REDUCE(P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN), [T_SEMI]=REDUCE(P_LHS_Nmimic_RHS_TLPAREN_TMIMIC_Nprec_atom_TRPAREN)},
/*  87 */	{[T_UNION]=SHIFT(77), [T_SEMI]=REDUCE(P_LHS_Nrhs_PRIME_RHS)},
/*  88 */	{[T_SEMI]=REDUCE(P_LHS_Nrhs_PRIME_RHS_TUNION_Nopt_list_Nmimic_Nrhs_PRIME)},
};

static int
fgfp_lr_goto_table[89][TOTAL_NTER] = {
/*   0 */	{[N_prec_section]=GOTO(6), [N_alias_section]=GOTO(5), [N_production_section]=GOTO(4), [N_extern_section]=GOTO(3), [N_section]=GOTO(2), [N_FGFP]=GOTO(1)},
/*   1 */	{},
/*   2 */	{[N_FGFP]=GOTO(15), [N_prec_section]=GOTO(6), [N_alias_section]=GOTO(5), [N_production_section]=GOTO(4), [N_extern_section]=GOTO(3), [N_section]=GOTO(2)},
/*   3 */	{},
/*   4 */	{},
/*   5 */	{},
/*   6 */	{},
/*   7 */	{},
/*   8 */	{},
/*   9 */	{},
/*  10 */	{},
/*  11 */	{[N_production]=GOTO(26), [N_production_list]=GOTO(25)},
/*  12 */	{[N_prec_dir]=GOTO(21), [N_prec_list]=GOTO(20)},
/*  13 */	{[N_alias_list]=GOTO(18)},
/*  14 */	{[N_path_list]=GOTO(16)},
/*  15 */	{},
/*  16 */	{},
/*  17 */	{[N_path_list_PRIME]=GOTO(38)},
/*  18 */	{},
/*  19 */	{},
/*  20 */	{},
/*  21 */	{},
/*  22 */	{},
/*  23 */	{},
/*  24 */	{},
/*  25 */	{},
/*  26 */	{[N_production]=GOTO(32), [N_production_list_PRIME]=GOTO(31)},
/*  27 */	{[N_follow_prod]=GOTO(28)},
/*  28 */	{},
/*  29 */	{},
/*  30 */	{[N_symbol]=GOTO(56), [N_symbol_list]=GOTO(54), [N_opt_list]=GOTO(53), [N_rhs]=GOTO(52)},
/*  31 */	{},
/*  32 */	{[N_production_list_PRIME]=GOTO(51), [N_production]=GOTO(32)},
/*  33 */	{},
/*  34 */	{[N_prec_atom]=GOTO(47), [N_prec_atom_list]=GOTO(46)},
/*  35 */	{},
/*  36 */	{},
/*  37 */	{},
/*  38 */	{},
/*  39 */	{[N_path_list]=GOTO(42)},
/*  40 */	{},
/*  41 */	{},
/*  42 */	{},
/*  43 */	{},
/*  44 */	{},
/*  45 */	{},
/*  46 */	{},
/*  47 */	{[N_prec_atom_list_PRIME]=GOTO(66)},
/*  48 */	{},
/*  49 */	{},
/*  50 */	{},
/*  51 */	{},
/*  52 */	{},
/*  53 */	{[N_mimic]=GOTO(64)},
/*  54 */	{},
/*  55 */	{},
/*  56 */	{[N_symbol]=GOTO(63), [N_symbol_list_PRIME]=GOTO(62)},
/*  57 */	{},
/*  58 */	{},
/*  59 */	{},
/*  60 */	{},
/*  61 */	{},
/*  62 */	{},
/*  63 */	{[N_symbol_list_PRIME]=GOTO(78), [N_symbol]=GOTO(63)},
/*  64 */	{[N_rhs_PRIME]=GOTO(76)},
/*  65 */	{},
/*  66 */	{},
/*  67 */	{[N_prec_atom]=GOTO(74), [N_prec_atom_list_PRIME_PRIME]=GOTO(73)},
/*  68 */	{[N_prec_list_PRIME]=GOTO(71)},
/*  69 */	{},
/*  70 */	{[N_alias_list_PRIME]=GOTO(83)},
/*  71 */	{},
/*  72 */	{[N_prec_list]=GOTO(82), [N_prec_dir]=GOTO(21)},
/*  73 */	{},
/*  74 */	{[N_prec_atom_list_PRIME]=GOTO(81)},
/*  75 */	{[N_prec_atom]=GOTO(80)},
/*  76 */	{},
/*  77 */	{[N_opt_list]=GOTO(79), [N_symbol]=GOTO(56), [N_symbol_list]=GOTO(54)},
/*  78 */	{},
/*  79 */	{[N_mimic]=GOTO(87)},
/*  80 */	{},
/*  81 */	{},
/*  82 */	{},
/*  83 */	{},
/*  84 */	{[N_alias_list]=GOTO(85)},
/*  85 */	{},
/*  86 */	{},
/*  87 */	{[N_rhs_PRIME]=GOTO(88)},
/*  88 */	{},
};

#endif

static int
fgfp_sync_token[TOTAL_NTER][6] = {
	[N_FGFP] = { T_EOF, -1 },
	[N_section] = { T_EXTERN, T_ALIAS, T_PRODUCTION, T_PRECEDENCE, T_EOF, -1 },
	[N_extern_section] = { T_EXTERN, T_ALIAS, T_PRODUCTION, T_PRECEDENCE, T_EOF, -1 },
	[N_production_section] = { T_EXTERN, T_ALIAS, T_PRODUCTION, T_PRECEDENCE, T_EOF, -1 },
	[N_alias_section] = { T_EXTERN, T_ALIAS, T_PRODUCTION, T_PRECEDENCE, T_EOF, -1 },
	[N_prec_section] = { T_EXTERN, T_ALIAS, T_PRODUCTION, T_PRECEDENCE, T_EOF, -1 },
	[N_path_list] = { T_RBRACE, -1 },
	[N_path_list_PRIME] = { T_RBRACE, -1 },
	[N_alias_list] = { T_RBRACE, -1 },
	[N_alias_list_PRIME] = { T_RBRACE, -1 },
	[N_prec_list] = { T_RBRACE, -1 },
	[N_prec_dir] = { T_LPAREN, -1 },
	[N_prec_atom_list] = { T_RPAREN, -1 },
	[N_prec_list_PRIME] = { T_RBRACE, -1 },
	[N_prec_atom] = { T_COMMA, T_RPAREN, -1 },
	[N_prec_atom_list_PRIME] = { T_RPAREN, -1 },
	[N_prec_atom_list_PRIME_PRIME] = { T_RPAREN, -1 },
	[N_production_list] = { T_RBRACE, -1 },
	[N_production] = { T_NTER, T_RBRACE, -1 },
	[N_production_list_PRIME] = { T_RBRACE, -1 },
	[N_follow_prod] = { T_SEMI, -1 },
	[N_rhs] = { T_SEMI, -1 },
	[N_opt_list] = { T_LPAREN, -1 },
	[N_mimic] = { T_SEMI, T_UNION, -1 },
	[N_rhs_PRIME] = { T_SEMI, -1 },
	[N_symbol_list] = { T_LPAREN, -1 },
	[N_symbol] = { T_LITERAL, T_GLOBAL_TOK, T_NTER, T_LPAREN, -1 },
	[N_symbol_list_PRIME] = { T_LPAREN, -1 },
};

#endif /* _FGFP_GRM_H_ */
