#ifndef _REGEX_GRM_H_
#define _REGEX_GRM_H_

#include <stdint.h>
#include <stdbool.h>

#define _ONLY_STATE_TOKEN_	
#include "fgfx.lex.h"
#undef	_ONLY_STATE_TOKEN_

enum {
	N_regex,
	OPT_N_regex_1_1,
	N_regex_look,
	N_regex_union,
	OPT_N_regex_look_1_1,
	N_regex_cat,
	LST_N_regex_union_1_1,
	N_regex_closure,
	LST_N_regex_cat_1_1,
	N_regex_atom,
	LST_N_regex_closure_1_1,
	N_finite_seq,
	OPT_N_finite_seq_1_1,
	OPT_N_finite_seq_1_2,
	N_fullccl,
	N_string,
	N_loneccl,
	LST_N_fullccl_1_1,
	N_kind_fullccl,
	OPT_N_loneccl_1_1,
	N_ccl,
	LST_N_ccl_1_1,
	OPT_N_ccl_1_2,
	LST_N_string_1_1,
};

#define TOTAL_NTER	24

enum {
	P_LHS_Nregex_RHS_OPTNregex_1_1,
	P_LHS_OPTNregex_1_1_RHS,
	P_LHS_OPTNregex_1_1_RHS_Nregex_look,
	P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1,
	P_LHS_OPTNregex_look_1_1_RHS,
	P_LHS_OPTNregex_look_1_1_RHS_TLOOK_Nregex_union,
	P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1,
	P_LHS_LSTNregex_union_1_1_RHS,
	P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1,
	P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1,
	P_LHS_LSTNregex_cat_1_1_RHS,
	P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1,
	P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1,
	P_LHS_LSTNregex_closure_1_1_RHS,
	P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1,
	P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1,
	P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1,
	P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1,
	P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE,
	P_LHS_OPTNfinite_seq_1_1_RHS,
	P_LHS_OPTNfinite_seq_1_1_RHS_TCOMMA_OPTNfinite_seq_1_2,
	P_LHS_OPTNfinite_seq_1_2_RHS,
	P_LHS_OPTNfinite_seq_1_2_RHS_TDIGIT,
	P_LHS_Nregex_atom_RHS_Nfullccl,
	P_LHS_Nregex_atom_RHS_Nstring,
	P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN,
	P_LHS_Nregex_atom_RHS_TDOT,
	P_LHS_Nregex_atom_RHS_TBOUND_NAME,
	P_LHS_Nregex_atom_RHS_TCHAR,
	P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1,
	P_LHS_LSTNfullccl_1_1_RHS,
	P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1,
	P_LHS_Nkind_fullccl_RHS_TDIFF_CLASS,
	P_LHS_Nkind_fullccl_RHS_TUNION_CLASS,
	P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK,
	P_LHS_OPTNloneccl_1_1_RHS,
	P_LHS_OPTNloneccl_1_1_RHS_TCARET,
	P_LHS_Nccl_RHS_LSTNccl_1_1,
	P_LHS_LSTNccl_1_1_RHS,
	P_LHS_LSTNccl_1_1_RHS_TCHAR_OPTNccl_1_2_LSTNccl_1_1,
	P_LHS_OPTNccl_1_2_RHS,
	P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR,
	P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE,
	P_LHS_LSTNstring_1_1_RHS,
	P_LHS_LSTNstring_1_1_RHS_TCHAR_LSTNstring_1_1,
};

#define TOTAL_PROD	46

static int
regex_rhs_prod_table[TOTAL_PROD] = {
	[P_LHS_Nregex_RHS_OPTNregex_1_1] = 1,
	[P_LHS_OPTNregex_1_1_RHS] = 0,
	[P_LHS_OPTNregex_1_1_RHS_Nregex_look] = 1,
	[P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1] = 2,
	[P_LHS_OPTNregex_look_1_1_RHS] = 0,
	[P_LHS_OPTNregex_look_1_1_RHS_TLOOK_Nregex_union] = 2,
	[P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1] = 2,
	[P_LHS_LSTNregex_union_1_1_RHS] = 0,
	[P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1] = 3,
	[P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1] = 2,
	[P_LHS_LSTNregex_cat_1_1_RHS] = 0,
	[P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1] = 2,
	[P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1] = 2,
	[P_LHS_LSTNregex_closure_1_1_RHS] = 0,
	[P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1] = 2,
	[P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1] = 2,
	[P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1] = 2,
	[P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1] = 2,
	[P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE] = 4,
	[P_LHS_OPTNfinite_seq_1_1_RHS] = 0,
	[P_LHS_OPTNfinite_seq_1_1_RHS_TCOMMA_OPTNfinite_seq_1_2] = 2,
	[P_LHS_OPTNfinite_seq_1_2_RHS] = 0,
	[P_LHS_OPTNfinite_seq_1_2_RHS_TDIGIT] = 1,
	[P_LHS_Nregex_atom_RHS_Nfullccl] = 1,
	[P_LHS_Nregex_atom_RHS_Nstring] = 1,
	[P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN] = 3,
	[P_LHS_Nregex_atom_RHS_TDOT] = 1,
	[P_LHS_Nregex_atom_RHS_TBOUND_NAME] = 1,
	[P_LHS_Nregex_atom_RHS_TCHAR] = 1,
	[P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1] = 2,
	[P_LHS_LSTNfullccl_1_1_RHS] = 0,
	[P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1] = 3,
	[P_LHS_Nkind_fullccl_RHS_TDIFF_CLASS] = 1,
	[P_LHS_Nkind_fullccl_RHS_TUNION_CLASS] = 1,
	[P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK] = 4,
	[P_LHS_OPTNloneccl_1_1_RHS] = 0,
	[P_LHS_OPTNloneccl_1_1_RHS_TCARET] = 1,
	[P_LHS_Nccl_RHS_LSTNccl_1_1] = 1,
	[P_LHS_LSTNccl_1_1_RHS] = 0,
	[P_LHS_LSTNccl_1_1_RHS_TCHAR_OPTNccl_1_2_LSTNccl_1_1] = 3,
	[P_LHS_OPTNccl_1_2_RHS] = 0,
	[P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR] = 2,
	[P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE] = 3,
	[P_LHS_LSTNstring_1_1_RHS] = 0,
	[P_LHS_LSTNstring_1_1_RHS_TCHAR_LSTNstring_1_1] = 2,
};

static int
regex_lhs_prod_table[TOTAL_PROD] = {
	[P_LHS_Nregex_RHS_OPTNregex_1_1] = N_regex,
	[P_LHS_OPTNregex_1_1_RHS] = OPT_N_regex_1_1,
	[P_LHS_OPTNregex_1_1_RHS_Nregex_look] = OPT_N_regex_1_1,
	[P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1] = N_regex_look,
	[P_LHS_OPTNregex_look_1_1_RHS] = OPT_N_regex_look_1_1,
	[P_LHS_OPTNregex_look_1_1_RHS_TLOOK_Nregex_union] = OPT_N_regex_look_1_1,
	[P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1] = N_regex_union,
	[P_LHS_LSTNregex_union_1_1_RHS] = LST_N_regex_union_1_1,
	[P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1] = LST_N_regex_union_1_1,
	[P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1] = N_regex_cat,
	[P_LHS_LSTNregex_cat_1_1_RHS] = LST_N_regex_cat_1_1,
	[P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1] = LST_N_regex_cat_1_1,
	[P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1] = N_regex_closure,
	[P_LHS_LSTNregex_closure_1_1_RHS] = LST_N_regex_closure_1_1,
	[P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1] = LST_N_regex_closure_1_1,
	[P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1] = LST_N_regex_closure_1_1,
	[P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1] = LST_N_regex_closure_1_1,
	[P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1] = LST_N_regex_closure_1_1,
	[P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE] = N_finite_seq,
	[P_LHS_OPTNfinite_seq_1_1_RHS] = OPT_N_finite_seq_1_1,
	[P_LHS_OPTNfinite_seq_1_1_RHS_TCOMMA_OPTNfinite_seq_1_2] = OPT_N_finite_seq_1_1,
	[P_LHS_OPTNfinite_seq_1_2_RHS] = OPT_N_finite_seq_1_2,
	[P_LHS_OPTNfinite_seq_1_2_RHS_TDIGIT] = OPT_N_finite_seq_1_2,
	[P_LHS_Nregex_atom_RHS_Nfullccl] = N_regex_atom,
	[P_LHS_Nregex_atom_RHS_Nstring] = N_regex_atom,
	[P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN] = N_regex_atom,
	[P_LHS_Nregex_atom_RHS_TDOT] = N_regex_atom,
	[P_LHS_Nregex_atom_RHS_TBOUND_NAME] = N_regex_atom,
	[P_LHS_Nregex_atom_RHS_TCHAR] = N_regex_atom,
	[P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1] = N_fullccl,
	[P_LHS_LSTNfullccl_1_1_RHS] = LST_N_fullccl_1_1,
	[P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1] = LST_N_fullccl_1_1,
	[P_LHS_Nkind_fullccl_RHS_TDIFF_CLASS] = N_kind_fullccl,
	[P_LHS_Nkind_fullccl_RHS_TUNION_CLASS] = N_kind_fullccl,
	[P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK] = N_loneccl,
	[P_LHS_OPTNloneccl_1_1_RHS] = OPT_N_loneccl_1_1,
	[P_LHS_OPTNloneccl_1_1_RHS_TCARET] = OPT_N_loneccl_1_1,
	[P_LHS_Nccl_RHS_LSTNccl_1_1] = N_ccl,
	[P_LHS_LSTNccl_1_1_RHS] = LST_N_ccl_1_1,
	[P_LHS_LSTNccl_1_1_RHS_TCHAR_OPTNccl_1_2_LSTNccl_1_1] = LST_N_ccl_1_1,
	[P_LHS_OPTNccl_1_2_RHS] = OPT_N_ccl_1_2,
	[P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR] = OPT_N_ccl_1_2,
	[P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE] = N_string,
	[P_LHS_LSTNstring_1_1_RHS] = LST_N_string_1_1,
	[P_LHS_LSTNstring_1_1_RHS_TCHAR_LSTNstring_1_1] = LST_N_string_1_1,
};

#define ERROR_SLOT	0
#define START_SYMBOL	N_regex

static int
regex_ll_table[TOTAL_NTER][TOTAL_TOKEN] = {
	[N_regex][T_EOF]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_QUOTE]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_DOT]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_LPAREN]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_LBRACK]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_CHAR]=P_LHS_Nregex_RHS_OPTNregex_1_1, [N_regex][T_BOUND_NAME]=P_LHS_Nregex_RHS_OPTNregex_1_1, 
	[OPT_N_regex_1_1][T_QUOTE]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_DOT]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_LPAREN]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_LBRACK]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_CHAR]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_BOUND_NAME]=P_LHS_OPTNregex_1_1_RHS_Nregex_look, [OPT_N_regex_1_1][T_EOF]=P_LHS_OPTNregex_1_1_RHS, 
	[N_regex_look][T_QUOTE]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, [N_regex_look][T_DOT]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, [N_regex_look][T_LPAREN]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, [N_regex_look][T_LBRACK]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, [N_regex_look][T_CHAR]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, [N_regex_look][T_BOUND_NAME]=P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1, 
	[N_regex_union][T_QUOTE]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, [N_regex_union][T_DOT]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, [N_regex_union][T_LPAREN]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, [N_regex_union][T_LBRACK]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, [N_regex_union][T_CHAR]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, [N_regex_union][T_BOUND_NAME]=P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1, 
	[OPT_N_regex_look_1_1][T_LOOK]=P_LHS_OPTNregex_look_1_1_RHS_TLOOK_Nregex_union, [OPT_N_regex_look_1_1][T_EOF]=P_LHS_OPTNregex_look_1_1_RHS, 
	[N_regex_cat][T_QUOTE]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, [N_regex_cat][T_DOT]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, [N_regex_cat][T_LPAREN]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, [N_regex_cat][T_LBRACK]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, [N_regex_cat][T_CHAR]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, [N_regex_cat][T_BOUND_NAME]=P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1, 
	[LST_N_regex_union_1_1][T_UNION]=P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1, [LST_N_regex_union_1_1][T_EOF]=P_LHS_LSTNregex_union_1_1_RHS, [LST_N_regex_union_1_1][T_RPAREN]=P_LHS_LSTNregex_union_1_1_RHS, [LST_N_regex_union_1_1][T_LOOK]=P_LHS_LSTNregex_union_1_1_RHS, 
	[N_regex_closure][T_QUOTE]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, [N_regex_closure][T_DOT]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, [N_regex_closure][T_LPAREN]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, [N_regex_closure][T_LBRACK]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, [N_regex_closure][T_CHAR]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, [N_regex_closure][T_BOUND_NAME]=P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1, 
	[LST_N_regex_cat_1_1][T_QUOTE]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_DOT]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_LPAREN]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_LBRACK]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_CHAR]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_BOUND_NAME]=P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1, [LST_N_regex_cat_1_1][T_EOF]=P_LHS_LSTNregex_cat_1_1_RHS, [LST_N_regex_cat_1_1][T_RPAREN]=P_LHS_LSTNregex_cat_1_1_RHS, [LST_N_regex_cat_1_1][T_UNION]=P_LHS_LSTNregex_cat_1_1_RHS, [LST_N_regex_cat_1_1][T_LOOK]=P_LHS_LSTNregex_cat_1_1_RHS, 
	[N_regex_atom][T_CHAR]=P_LHS_Nregex_atom_RHS_TCHAR, [N_regex_atom][T_BOUND_NAME]=P_LHS_Nregex_atom_RHS_TBOUND_NAME, [N_regex_atom][T_DOT]=P_LHS_Nregex_atom_RHS_TDOT, [N_regex_atom][T_LPAREN]=P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN, [N_regex_atom][T_QUOTE]=P_LHS_Nregex_atom_RHS_Nstring, [N_regex_atom][T_LBRACK]=P_LHS_Nregex_atom_RHS_Nfullccl, 
	[LST_N_regex_closure_1_1][T_LBRACE]=P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1, [LST_N_regex_closure_1_1][T_QUES]=P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1, [LST_N_regex_closure_1_1][T_PLUS]=P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1, [LST_N_regex_closure_1_1][T_STAR]=P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1, [LST_N_regex_closure_1_1][T_EOF]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_QUOTE]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_DOT]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_RPAREN]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_LPAREN]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_LBRACK]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_UNION]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_LOOK]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_CHAR]=P_LHS_LSTNregex_closure_1_1_RHS, [LST_N_regex_closure_1_1][T_BOUND_NAME]=P_LHS_LSTNregex_closure_1_1_RHS, 
	[N_finite_seq][T_LBRACE]=P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE, 
	[OPT_N_finite_seq_1_1][T_COMMA]=P_LHS_OPTNfinite_seq_1_1_RHS_TCOMMA_OPTNfinite_seq_1_2, [OPT_N_finite_seq_1_1][T_RBRACE]=P_LHS_OPTNfinite_seq_1_1_RHS, 
	[OPT_N_finite_seq_1_2][T_DIGIT]=P_LHS_OPTNfinite_seq_1_2_RHS_TDIGIT, [OPT_N_finite_seq_1_2][T_RBRACE]=P_LHS_OPTNfinite_seq_1_2_RHS, 
	[N_fullccl][T_LBRACK]=P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1, 
	[N_string][T_QUOTE]=P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE, 
	[N_loneccl][T_LBRACK]=P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK, 
	[LST_N_fullccl_1_1][T_UNION_CLASS]=P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1, [LST_N_fullccl_1_1][T_DIFF_CLASS]=P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1, [LST_N_fullccl_1_1][T_EOF]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_QUOTE]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_DOT]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_RPAREN]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_LPAREN]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_LBRACE]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_LBRACK]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_QUES]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_PLUS]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_STAR]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_UNION]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_LOOK]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_CHAR]=P_LHS_LSTNfullccl_1_1_RHS, [LST_N_fullccl_1_1][T_BOUND_NAME]=P_LHS_LSTNfullccl_1_1_RHS, 
	[N_kind_fullccl][T_UNION_CLASS]=P_LHS_Nkind_fullccl_RHS_TUNION_CLASS, [N_kind_fullccl][T_DIFF_CLASS]=P_LHS_Nkind_fullccl_RHS_TDIFF_CLASS, 
	[OPT_N_loneccl_1_1][T_CARET]=P_LHS_OPTNloneccl_1_1_RHS_TCARET, [OPT_N_loneccl_1_1][T_RBRACK]=P_LHS_OPTNloneccl_1_1_RHS, [OPT_N_loneccl_1_1][T_CHAR]=P_LHS_OPTNloneccl_1_1_RHS, 
	[N_ccl][T_RBRACK]=P_LHS_Nccl_RHS_LSTNccl_1_1, [N_ccl][T_CHAR]=P_LHS_Nccl_RHS_LSTNccl_1_1, 
	[LST_N_ccl_1_1][T_CHAR]=P_LHS_LSTNccl_1_1_RHS_TCHAR_OPTNccl_1_2_LSTNccl_1_1, [LST_N_ccl_1_1][T_RBRACK]=P_LHS_LSTNccl_1_1_RHS, 
	[OPT_N_ccl_1_2][T_HYPHEN]=P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR, [OPT_N_ccl_1_2][T_RBRACK]=P_LHS_OPTNccl_1_2_RHS, [OPT_N_ccl_1_2][T_CHAR]=P_LHS_OPTNccl_1_2_RHS, 
	[LST_N_string_1_1][T_CHAR]=P_LHS_LSTNstring_1_1_RHS_TCHAR_LSTNstring_1_1, [LST_N_string_1_1][T_QUOTE]=P_LHS_LSTNstring_1_1_RHS, 
};

#if 0

enum {
	_SHIFT	= 0x1000,
	_REDUCE	= 0x2000,
	_GOTO	= 0x4000,
};

#define SHIFT(x)	(x | _SHIFT)
#define REDUCE(x)	(x | _REDUCE)
#define GOTO(x)	(x | _GOTO)
#define ACCEPT	(~0)

#define LR_START_STATE	0

static int
regex_lr_action_table[65][TOTAL_TOKEN] = {
/*   0 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10), [T_EOF]=REDUCE(P_LHS_OPTNregex_1_1_RHS)},
/*   1 */	{[T_EOF]=ACCEPT,},
/*   2 */	{[T_EOF]=REDUCE(P_LHS_Nregex_RHS_OPTNregex_1_1)},
/*   3 */	{[T_EOF]=REDUCE(P_LHS_OPTNregex_1_1_RHS_Nregex_look)},
/*   4 */	{[T_LOOK]=SHIFT(63), [T_EOF]=REDUCE(P_LHS_OPTNregex_look_1_1_RHS)},
/*   5 */	{[T_UNION]=SHIFT(58), [T_EOF]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS)},
/*   6 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10), [T_EOF]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS)},
/*   7 */	{[T_LBRACE]=SHIFT(43), [T_QUES]=SHIFT(41), [T_PLUS]=SHIFT(40), [T_STAR]=SHIFT(39), [T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS)},
/*   8 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_RPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_Nfullccl)},
/*   9 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_RPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_Nstring)},
/*  10 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10)},
/*  11 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_RPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_TDOT)},
/*  12 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_RPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_TBOUND_NAME)},
/*  13 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_RPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_TCHAR)},
/*  14 */	{[T_UNION_CLASS]=SHIFT(34), [T_DIFF_CLASS]=SHIFT(33), [T_EOF]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LBRACE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_QUES]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_PLUS]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_STAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS)},
/*  15 */	{[T_CARET]=SHIFT(22), [T_RBRACK]=REDUCE(P_LHS_OPTNloneccl_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_OPTNloneccl_1_1_RHS)},
/*  16 */	{[T_CHAR]=SHIFT(18), [T_QUOTE]=REDUCE(P_LHS_LSTNstring_1_1_RHS)},
/*  17 */	{[T_QUOTE]=SHIFT(20)},
/*  18 */	{[T_CHAR]=SHIFT(18), [T_QUOTE]=REDUCE(P_LHS_LSTNstring_1_1_RHS)},
/*  19 */	{[T_QUOTE]=REDUCE(P_LHS_LSTNstring_1_1_RHS_TCHAR_LSTNstring_1_1)},
/*  20 */	{[T_EOF]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_QUOTE]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_DOT]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_RPAREN]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_LPAREN]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_LBRACE]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_LBRACK]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_QUES]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_PLUS]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_STAR]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_UNION]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_LOOK]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_CHAR]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE), [T_BOUND_NAME]=REDUCE(P_LHS_Nstring_RHS_TQUOTE_LSTNstring_1_1_TQUOTE)},
/*  21 */	{[T_CHAR]=SHIFT(25), [T_RBRACK]=REDUCE(P_LHS_LSTNccl_1_1_RHS)},
/*  22 */	{[T_RBRACK]=REDUCE(P_LHS_OPTNloneccl_1_1_RHS_TCARET), [T_CHAR]=REDUCE(P_LHS_OPTNloneccl_1_1_RHS_TCARET)},
/*  23 */	{[T_RBRACK]=SHIFT(30)},
/*  24 */	{[T_RBRACK]=REDUCE(P_LHS_Nccl_RHS_LSTNccl_1_1)},
/*  25 */	{[T_HYPHEN]=SHIFT(27), [T_RBRACK]=REDUCE(P_LHS_OPTNccl_1_2_RHS), [T_CHAR]=REDUCE(P_LHS_OPTNccl_1_2_RHS)},
/*  26 */	{[T_CHAR]=SHIFT(25), [T_RBRACK]=REDUCE(P_LHS_LSTNccl_1_1_RHS)},
/*  27 */	{[T_CHAR]=SHIFT(28)},
/*  28 */	{[T_RBRACK]=REDUCE(P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR), [T_CHAR]=REDUCE(P_LHS_OPTNccl_1_2_RHS_THYPHEN_TCHAR)},
/*  29 */	{[T_RBRACK]=REDUCE(P_LHS_LSTNccl_1_1_RHS_TCHAR_OPTNccl_1_2_LSTNccl_1_1)},
/*  30 */	{[T_EOF]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_QUOTE]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_DOT]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_RPAREN]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_LPAREN]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_LBRACE]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_LBRACK]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_QUES]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_PLUS]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_STAR]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_UNION]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_LOOK]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_UNION_CLASS]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_DIFF_CLASS]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_CHAR]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK), [T_BOUND_NAME]=REDUCE(P_LHS_Nloneccl_RHS_TLBRACK_OPTNloneccl_1_1_Nccl_TRBRACK)},
/*  31 */	{[T_EOF]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_QUOTE]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_DOT]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_RPAREN]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_LPAREN]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_LBRACE]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_LBRACK]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_QUES]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_PLUS]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_STAR]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_UNION]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_LOOK]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_CHAR]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_Nfullccl_RHS_Nloneccl_LSTNfullccl_1_1)},
/*  32 */	{[T_LBRACK]=SHIFT(15)},
/*  33 */	{[T_LBRACK]=REDUCE(P_LHS_Nkind_fullccl_RHS_TDIFF_CLASS)},
/*  34 */	{[T_LBRACK]=REDUCE(P_LHS_Nkind_fullccl_RHS_TUNION_CLASS)},
/*  35 */	{[T_UNION_CLASS]=SHIFT(34), [T_DIFF_CLASS]=SHIFT(33), [T_EOF]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LBRACE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_QUES]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_PLUS]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_STAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS)},
/*  36 */	{[T_EOF]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_QUOTE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_DOT]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_LPAREN]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_LBRACE]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_LBRACK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_QUES]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_PLUS]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_STAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_UNION]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_CHAR]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNfullccl_1_1_RHS_Nkind_fullccl_Nloneccl_LSTNfullccl_1_1)},
/*  37 */	{[T_RPAREN]=SHIFT(61)},
/*  38 */	{[T_EOF]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_QUOTE]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_DOT]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_RPAREN]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_LPAREN]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_LBRACK]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_UNION]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_LOOK]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_CHAR]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_closure_RHS_Nregex_atom_LSTNregex_closure_1_1)},
/*  39 */	{[T_LBRACE]=SHIFT(43), [T_QUES]=SHIFT(41), [T_PLUS]=SHIFT(40), [T_STAR]=SHIFT(39), [T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS)},
/*  40 */	{[T_LBRACE]=SHIFT(43), [T_QUES]=SHIFT(41), [T_PLUS]=SHIFT(40), [T_STAR]=SHIFT(39), [T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS)},
/*  41 */	{[T_LBRACE]=SHIFT(43), [T_QUES]=SHIFT(41), [T_PLUS]=SHIFT(40), [T_STAR]=SHIFT(39), [T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS)},
/*  42 */	{[T_LBRACE]=SHIFT(43), [T_QUES]=SHIFT(41), [T_PLUS]=SHIFT(40), [T_STAR]=SHIFT(39), [T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS)},
/*  43 */	{[T_DIGIT]=SHIFT(44)},
/*  44 */	{[T_COMMA]=SHIFT(46), [T_RBRACE]=REDUCE(P_LHS_OPTNfinite_seq_1_1_RHS)},
/*  45 */	{[T_RBRACE]=SHIFT(49)},
/*  46 */	{[T_DIGIT]=SHIFT(48), [T_RBRACE]=REDUCE(P_LHS_OPTNfinite_seq_1_2_RHS)},
/*  47 */	{[T_RBRACE]=REDUCE(P_LHS_OPTNfinite_seq_1_1_RHS_TCOMMA_OPTNfinite_seq_1_2)},
/*  48 */	{[T_RBRACE]=REDUCE(P_LHS_OPTNfinite_seq_1_2_RHS_TDIGIT)},
/*  49 */	{[T_EOF]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_QUOTE]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_DOT]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_RPAREN]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_LPAREN]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_LBRACE]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_LBRACK]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_QUES]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_PLUS]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_STAR]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_UNION]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_LOOK]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_CHAR]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE), [T_BOUND_NAME]=REDUCE(P_LHS_Nfinite_seq_RHS_TLBRACE_TDIGIT_OPTNfinite_seq_1_1_TRBRACE)},
/*  50 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_Nfinite_seq_LSTNregex_closure_1_1)},
/*  51 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TQUES_LSTNregex_closure_1_1)},
/*  52 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TPLUS_LSTNregex_closure_1_1)},
/*  53 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_QUOTE]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_DOT]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_LPAREN]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_LBRACK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_UNION]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_CHAR]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1), [T_BOUND_NAME]=REDUCE(P_LHS_LSTNregex_closure_1_1_RHS_TSTAR_LSTNregex_closure_1_1)},
/*  54 */	{[T_EOF]=REDUCE(P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_RPAREN]=REDUCE(P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_UNION]=REDUCE(P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_LOOK]=REDUCE(P_LHS_Nregex_cat_RHS_Nregex_closure_LSTNregex_cat_1_1)},
/*  55 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10), [T_EOF]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_UNION]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS)},
/*  56 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_UNION]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_cat_1_1_RHS_Nregex_closure_LSTNregex_cat_1_1)},
/*  57 */	{[T_EOF]=REDUCE(P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1), [T_RPAREN]=REDUCE(P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1), [T_LOOK]=REDUCE(P_LHS_Nregex_union_RHS_Nregex_cat_LSTNregex_union_1_1)},
/*  58 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10)},
/*  59 */	{[T_UNION]=SHIFT(58), [T_EOF]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS), [T_LOOK]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS)},
/*  60 */	{[T_EOF]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1), [T_RPAREN]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1), [T_LOOK]=REDUCE(P_LHS_LSTNregex_union_1_1_RHS_TUNION_Nregex_cat_LSTNregex_union_1_1)},
/*  61 */	{[T_EOF]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_QUOTE]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_DOT]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_LPAREN]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_LBRACE]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_LBRACK]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_QUES]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_PLUS]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_STAR]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_UNION]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_LOOK]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_CHAR]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN), [T_BOUND_NAME]=REDUCE(P_LHS_Nregex_atom_RHS_TLPAREN_Nregex_union_TRPAREN)},
/*  62 */	{[T_EOF]=REDUCE(P_LHS_Nregex_look_RHS_Nregex_union_OPTNregex_look_1_1)},
/*  63 */	{[T_QUOTE]=SHIFT(16), [T_LBRACK]=SHIFT(15), [T_CHAR]=SHIFT(13), [T_BOUND_NAME]=SHIFT(12), [T_DOT]=SHIFT(11), [T_LPAREN]=SHIFT(10)},
/*  64 */	{[T_EOF]=REDUCE(P_LHS_OPTNregex_look_1_1_RHS_TLOOK_Nregex_union)},
};

static int
regex_lr_goto_table[65][TOTAL_NTER] = {
/*   0 */	{[N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7), [N_regex_closure]=GOTO(6), [N_regex_cat]=GOTO(5), [N_regex_union]=GOTO(4), [N_regex_look]=GOTO(3), [OPT_N_regex_1_1]=GOTO(2), [N_regex]=GOTO(1)},
/*   1 */	{},
/*   2 */	{},
/*   3 */	{},
/*   4 */	{[OPT_N_regex_look_1_1]=GOTO(62)},
/*   5 */	{[LST_N_regex_union_1_1]=GOTO(57)},
/*   6 */	{[N_regex_closure]=GOTO(55), [LST_N_regex_cat_1_1]=GOTO(54), [N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7)},
/*   7 */	{[N_finite_seq]=GOTO(42), [LST_N_regex_closure_1_1]=GOTO(38)},
/*   8 */	{},
/*   9 */	{},
/*  10 */	{[N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7), [N_regex_closure]=GOTO(6), [N_regex_cat]=GOTO(5), [N_regex_union]=GOTO(37)},
/*  11 */	{},
/*  12 */	{},
/*  13 */	{},
/*  14 */	{[N_kind_fullccl]=GOTO(32), [LST_N_fullccl_1_1]=GOTO(31)},
/*  15 */	{[OPT_N_loneccl_1_1]=GOTO(21)},
/*  16 */	{[LST_N_string_1_1]=GOTO(17)},
/*  17 */	{},
/*  18 */	{[LST_N_string_1_1]=GOTO(19)},
/*  19 */	{},
/*  20 */	{},
/*  21 */	{[LST_N_ccl_1_1]=GOTO(24), [N_ccl]=GOTO(23)},
/*  22 */	{},
/*  23 */	{},
/*  24 */	{},
/*  25 */	{[OPT_N_ccl_1_2]=GOTO(26)},
/*  26 */	{[LST_N_ccl_1_1]=GOTO(29)},
/*  27 */	{},
/*  28 */	{},
/*  29 */	{},
/*  30 */	{},
/*  31 */	{},
/*  32 */	{[N_loneccl]=GOTO(35)},
/*  33 */	{},
/*  34 */	{},
/*  35 */	{[LST_N_fullccl_1_1]=GOTO(36), [N_kind_fullccl]=GOTO(32)},
/*  36 */	{},
/*  37 */	{},
/*  38 */	{},
/*  39 */	{[LST_N_regex_closure_1_1]=GOTO(53), [N_finite_seq]=GOTO(42)},
/*  40 */	{[LST_N_regex_closure_1_1]=GOTO(52), [N_finite_seq]=GOTO(42)},
/*  41 */	{[LST_N_regex_closure_1_1]=GOTO(51), [N_finite_seq]=GOTO(42)},
/*  42 */	{[LST_N_regex_closure_1_1]=GOTO(50), [N_finite_seq]=GOTO(42)},
/*  43 */	{},
/*  44 */	{[OPT_N_finite_seq_1_1]=GOTO(45)},
/*  45 */	{},
/*  46 */	{[OPT_N_finite_seq_1_2]=GOTO(47)},
/*  47 */	{},
/*  48 */	{},
/*  49 */	{},
/*  50 */	{},
/*  51 */	{},
/*  52 */	{},
/*  53 */	{},
/*  54 */	{},
/*  55 */	{[LST_N_regex_cat_1_1]=GOTO(56), [N_regex_closure]=GOTO(55), [N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7)},
/*  56 */	{},
/*  57 */	{},
/*  58 */	{[N_regex_closure]=GOTO(6), [N_regex_cat]=GOTO(59), [N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7)},
/*  59 */	{[LST_N_regex_union_1_1]=GOTO(60)},
/*  60 */	{},
/*  61 */	{},
/*  62 */	{},
/*  63 */	{[N_loneccl]=GOTO(14), [N_string]=GOTO(9), [N_fullccl]=GOTO(8), [N_regex_atom]=GOTO(7), [N_regex_closure]=GOTO(6), [N_regex_cat]=GOTO(5), [N_regex_union]=GOTO(64)},
/*  64 */	{},
};

#endif

static int
regex_sync_token[TOTAL_NTER][17] = {
	[N_regex] = { T_EOF, -1 },
	[OPT_N_regex_1_1] = { T_EOF, -1 },
	[N_regex_look] = { T_EOF, -1 },
	[N_regex_union] = { T_LOOK, T_RPAREN, T_EOF, -1 },
	[OPT_N_regex_look_1_1] = { T_EOF, -1 },
	[N_regex_cat] = { T_LOOK, T_UNION, T_RPAREN, T_EOF, -1 },
	[LST_N_regex_union_1_1] = { T_LOOK, T_RPAREN, T_EOF, -1 },
	[N_regex_closure] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_LBRACK, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[LST_N_regex_cat_1_1] = { T_LOOK, T_UNION, T_RPAREN, T_EOF, -1 },
	[N_regex_atom] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[LST_N_regex_closure_1_1] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_LBRACK, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[N_finite_seq] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[OPT_N_finite_seq_1_1] = { T_RBRACE, -1 },
	[OPT_N_finite_seq_1_2] = { T_RBRACE, -1 },
	[N_fullccl] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[N_string] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[N_loneccl] = { T_BOUND_NAME, T_CHAR, T_DIFF_CLASS, T_UNION_CLASS, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[LST_N_fullccl_1_1] = { T_BOUND_NAME, T_CHAR, T_LOOK, T_UNION, T_STAR, T_PLUS, T_QUES, T_LBRACK, T_LBRACE, T_LPAREN, T_RPAREN, T_DOT, T_QUOTE, T_EOF, -1 },
	[N_kind_fullccl] = { T_LBRACK, -1 },
	[OPT_N_loneccl_1_1] = { T_CHAR, T_RBRACK, -1 },
	[N_ccl] = { T_RBRACK, -1 },
	[LST_N_ccl_1_1] = { T_RBRACK, -1 },
	[OPT_N_ccl_1_2] = { T_CHAR, T_RBRACK, -1 },
	[LST_N_string_1_1] = { T_QUOTE, -1 },
};

#endif /* _REGEX_GRM_H_ */
